name: Release

on:
  push:
    paths-ignore:
      - CHANGELOG.md
      - package.json
    branches:
      - master
  repository_dispatch:
    types: [semantic-release]

jobs:
  release:
    if: "!contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch tags
        run: git fetch --prune --unshallow --tags
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        run: npm ci
      - name: Github release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: VS Code Marketplace
        run: npx vsce publish
        env:
          VSCE_PAT: ${{secrets.VSCE_PAT}}
